### ISSUE TITLE
application name not prepended to logs

### ISSUE THREAD

**Issue by pkoniu** [gajus/roarr#10]
Found another one (this time on `2.3.0`). So I have a file in my project that looks exactly like this:
``` javascript
const roarr = require('roarr').default;

global.ROARR.prepend = {
  ...global.ROARR.prepend,
  application: 'test-app',
};

module.exports = settings => roarr.child(settings);
```
And then I require that file everywhere where needed and create a child with additional property `namespace`. Like this:
``` javascript
const loggerFactory = require('./logger-factory');
const logger = loggerFactory({ namespace: 'test-namespace' });
logger.info('lorem ipsum');
```
On `2.0.2` it worked perfectly I had application name prepended to every log and namespace accrodingly. Unfortunately on `2.3.0` it does not work, roarr does not add application property to context.

I did look through readme this time before posting an issue but didn't find any related information about this.

**Comment by gajus** [comment]
https://github.com/gajus/roarr/commit/dffac37030d0d2db3e75cd3e91235eef69dbc839

Sorry.
