### ISSUE TITLE
Rotating files?

### ISSUE THREAD

**Issue by normancarcamo** [gajus/roarr#16]
**How can I rotate files with roarr?**

I couldn't find infomation about this in the docs on Github, do you recommend something to workaround this?

Rotating files is something useful too and that's the only thing that I couldn't find here, the rest is a good logger as far I can see.

thanks.

**Comment by gajus** [comment]
Rotating logs is not a responsibility of an application layer logger.

I suggest taking a look at https://github.com/logrotate/logrotate.

**Comment by normancarcamo** [comment]
Thanks for the note of the layer, I didn't realized it, as well thanks for the repo I'm looking at it now :)

**Comment by normancarcamo** [comment]
I answer this to close it, I know now the reason and make it sense when it's referred to the single thread :(
