### ISSUE TITLE
Adding namespace to the context

### ISSUE THREAD

**Issue by webernir** [gajus/roarr#17]
@gajus In the README conventions suggestions you mentioned 'namespace'. How would you go about and add namespace as another context property?
Should i instanciate a new log child with the name of the file/module/class?

What I want is to log the file and the line of code which produces the log. Is there any recommended way to do so?

**Comment by gajus** [comment]
> What I want is to log the file and the line of code which produces the log. Is there any recommended way to do so?

This would be extremely slow if done at a runtime.

You would need to create a callstack for every log message.
