### ISSUE TITLE
Browser usage

### ISSUE THREAD

**Issue by mickdekkers** [gajus/roarr#2]
Hello! I read your [Medium post](https://medium.com/@gajus/roarr-the-perfect-json-logger-node-js-and-browser-935180bda529) and this package seems to be exactly what I'm looking for :)

You mentioned it can be used in the browser as well, could you share an example of how this would work?
Since `process.stdout` isn't available in browser environments, I'm not sure where the logs would be sent.

I'd imagine they'd be sent to some logging server while being visible to some degree in the browser console as well. Unfortunately, the browser console doesn't really provide a way to filter the logs like you would be able to with node and `jq`. Perhaps this part could be handled by a browser extension?

**Comment by gajus** [comment]
> I'd imagine they'd be sent to some logging server while being visible to some degree in the browser console as well. Unfortunately, the browser console doesn't really provide a way to filter the logs like you would be able to with node and jq. Perhaps this part could be handled by a browser extension?

There is no browser support at the moment.

I left it out until I have a better idea of how to handle the logs in the browser. Simply using `console.log` for everything is unsustainable.

I think, the best solution is to use a global variable that would be invoked for every log message, e.g. `window.ROARR.on('message', () => {})` and leave it up to the application to decide what it wants to do with the logs, including filtering, transports, etc.

Thoughts?

**Comment by mickdekkers** [comment]
> I think, the best solution is to use a global variable that would be invoked for every log message, e.g. `window.ROARR.on('message', () => {})` and leave it up to the application to decide what it wants to do with the logs, including filtering, transports, etc.

This definitely sounds reasonable and it's probably the most flexible solution. It also wouldn't exclude the future possibility of a log viewer browser extension I hinted at earlier (it could simply hook into that global `message` event).

I agree the application should be able to decide how to filter/transport/format the messages, but it wouldn't hurt to make common use cases easy to set up. For example, by adding some sort of prettify function to make logging to the browser console easier during development.

```js
// Pretty print messages to the browser console
window.ROARR.on('message', message => console.log(ROARR.prettify(message)))
```

This might print something similar to the CLI pretty printer, but possibly more optimized to take advantage of browser console APIs (e.g. [coloring and styling the messages using CSS](https://stackoverflow.com/a/13017382/1233003)). Though `prettify` might be a bit too generic a function name for this.

**Comment by gajus** [comment]
I will implement the first part – `window.ROARR.on('message')`.

Will open a second issue to discuss log viewer in a browser. I think it should be a separate project.

**Comment by mickdekkers** [comment]
> I will implement the first part – `window.ROARR.on('message')`.

Great!

> Will open a second issue to discuss log viewer in a browser. I think it should be a separate project, maybe even a browser extension.

I'd be willing to contribute to such a project 🙂

**Comment by sebinsua** [comment]
Is this still true?

The summary of the repository says:

> JSON logger for Node.js and browser.

However, I noticed that [in the browser you don't support transports](https://github.com/gajus/roarr#transports). That would make this logger much less useful for browsers if it's true.

**Comment by gajus** [comment]
> However, I noticed that in the browser you don't support transports. That would make this logger much less useful for browsers if it's true.

I have not had a use case for logging in browser using roarr.

I agree though, it should definitely be sorted. Ideally, by someone who have a use case and can test it in real-world setup.

What do you think about the `window.ROARR.on('message')` approach?

If you like the approach, could you work on the implementation?

**Comment by gkohen** [comment]
First of all I want to commend the abilities of this library. Great work!
I do think, however, the summary description should be change to reflect what it support as it's misleading.

**Comment by gajus** [comment]
> First of all I want to commend the abilities of this library. Great work!
> I do think, however, the summary description should be change to reflect what it support as it's misleading.

I agree, but the side-effect of that message has been that it enabled to evaluate the demand for the feature. 👍 is a good approximation of how many people want this feature.

I think the `window.ROARR.on('message')` approach would work (or even using window object to fire custom events). However, I do not want to lead development of the feature as currently I do not have a use case to test logging in browser environment. It is one thing to develop a feature in a theoretical environment and a completely different case developing a feature when you have a use case.

**Comment by grantcarthew** [comment]
Hey, until browser support is added checkout [perj](https://github.com/grantcarthew/node-perj). One of its goals is to be cross platform. I recently released v2 which improved stringification of browser objects.

**Comment by zamzowd** [comment]
The description shouldn't claim to support the browser (especially in the first line) if it does not work in the browser.  If you want to gauge demand, then just have a comment like "If you'd like to use this in the browser, vote here" and link to this issue.

As is, it just seems intentionally deceptive.

**Comment by Everlag** [comment]
Opened https://github.com/gajus/roarr/pull/22 after having invested time in integrating this package to a browser-targeted package then discovered roarr does not support browsers.

This is a great logger and I want to use it but lack of even rudimentary browser support is a dealbreaker.

**Comment by gajus** [comment]
Sorry everyone this took a while.

With help of @ron4ex, I have updated the logger to add browser support.

https://github.com/gajus/roarr/commit/173dc8c6fe9c396a7eadd7167dd03f30b5201f52

It works by configuring `globalThis.ROARR.write` method, e.g.

```js
// Ensure that `globalThis.ROARR` is configured.
globalThis.ROARR = globalThis.ROARR || {};

globalThis.ROARR.write = (message) => {
  console.log(JSON.parse(message));
};

```
