### ISSUE TITLE
node 10 required

### ISSUE THREAD

**Issue by obartra** [gajus/roarr#25]
Looks like the 1.0.0 release updated the `boolean` package which requires Node 10 or above (since it uses regex capture groups).

I was wondering if you would consider locking the version of that package in order for roarr to support older versions of node.

Happy to contribute if you have a recommended path forward for roarr.

This is the error I'm getting on node 8.16.1

```sh
{path}/node_modules/roarr/node_modules/boolean/build/lib/boolean.js:5
        return /^(?<truthy>true|t|yes|y|on|1)$/iu.test(value.trim());
        ^

SyntaxError: Invalid regular expression: /^(?<truthy>true|t|yes|y|on|1)$/: Invalid group
    at boolean (/{path}/node_modules/roarr/node_modules/boolean/build/lib/boolean.js:5:9)
    at Object.<anonymous> (/{path}/node_modules/roarr/dist/log.js:24:38)
```

**Comment by gajus** [comment]
First let's see if this can be fixed upstream.

https://github.com/thenativeweb/boolean/issues/21

**Comment by obartra** [comment]
Thanks for the quick reply! Looks like both upstream thenativeweb/boolean#21 and downstream (for me) https://github.com/renovatebot/renovate/issues/4696, require latest node. I may just do the update or lock dependencies then. Thanks for the help though!
