### ISSUE TITLE
Use numbers instead of strings to represent log levels

### ISSUE THREAD

**Issue by hbarcelos** [gajus/roarr#3]
I believe that, like other loggers available out there, Roarr should represent log level internally as number to ease filtering using `jq` or building queries on log storage/search engines.

Imagine I want to log all levels, except by `trace`. Then I'd have to have:

```bash
jq 'select(.context.logLevel == "debug" or .context.logLevel == "info" or .context.logLevel == "warn" or .context.logLevel == "error" or .context.logLevel == "fatal")'
```

If Roarr were to attribute a numeric value to all levels, like:

- `silly`: 10
- `debug`: 20
- `info`: 30
- `warn`: 40
- `error`: 50
- `fatal`: 60

Then that `jq` expression would be reduced to:

```bash
jq 'select(.context.logLevel > 10)'
```

Makes sense?

**Comment by gajus** [comment]
Absolutely. It can be added as an additional property, e.g. `logLevelWeight`. Unless you have suggestion for a better name?

**Comment by hbarcelos** [comment]
I don't mean to sound petty or the early-optimizer type, but I'm not sure about the implications of having an extra property.

I believe that a property with `"error"` as its value doesn't add much information to a computer-friendly format like JSON. This is meant for humans. 

Adding `,"logLevelWeight":10` to every log entry adds 21 bytes of redundant information. 

Just trying to make some back-of-the-envelope math here. Imagine a mid-sized application that deals with 50,000 requests per day. Imagine also that each request creates 10 log entries, so we are talking about 500,000 log entries per day.

Those extra bytes 21 represent:

- 10,5 GB in 1 day
- 315 GB in 1 month
- 3,78 TB in 1 year

For larger applications, this might become out of hand. (One might argue that larger applications should do some kind of sampling on their logs, but I fundamentally disagree with this).

So I believe that the only information needed in the JSON generated by Roarr should be the `logLevel` as an integer. Then tools for humans like `pretty-print`, majorly used during development, should be responsible to translate `10` into `SILLY`.

**Comment by gajus** [comment]
Done
