### ISSUE TITLE
Printf arguments README

### ISSUE THREAD

**Issue by teukuamru** [gajus/roarr#32]
I think the readme at https://github.com/gajus/roarr#api `Printf arguments must be of a primitive type (string | number | boolean | null)` should be updated to `string | number | boolean | object | null` because printf could handle object argument

Note:
I'm using typescript and the https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/roarr follows the documentation of this readme

**Comment by gajus** [comment]
The documented types are the only ones that are guaranteed to work and they are consistent with the local Flowtype types.

https://github.com/gajus/roarr/blob/master/src/types.js#L22
