### ISSUE TITLE
Roarr drop error?

### ISSUE THREAD

**Issue by dmpvost** [gajus/roarr#35]
sometimes, I have the feeling that roarr drop some error.

console.log("e:",error) give me that : 

Is it because the errorMessage is inside stack?

On typing error by example:

```
e: TypeError: Cannot read property 'oneFirst' of undefined at ... [stack]

```

and with roarr

```
log.error({e: e}, "ERROR IN getLanguageConfigDB : ");
```

```
[DATE] ERROR (50) (@getLanguageConfigDB) (#TzHiSKm0CaA6M7UVAAAA): ERROR IN getLanguageConfigDB : 
e: (empty YAML)

```

There is no details, did I something wrong? 

there is a bug?

**Comment by gajus** [comment]
You need to use [serialize-error](https://www.npmjs.com/package/serialize-error), e.g.

```js
import {serializeError} from 'serialize-error';

log.error({
  error: serializeError(error),
}, 'my error');
```

**Comment by gajus** [comment]
You can also use a middleware to automate this.

https://github.com/gajus/roarr#middlewares

**Comment by dmpvost** [comment]
Wow this is great! 👍 Thank you gajus ;)

**Comment by dmpvost** [comment]
I didn't understand this part of the documentation first time i read it.

There was already so much information that I realize that i dropped it

**Comment by Madd0g** [comment]
I kept getting swallowed errors that didn't make sense, then after exhausting every other single option, I decided to add try-catch around my logger `log.error({error:err})`.

```js
const log = logger.child({ namespace: 'whatever' })
try {
    // ... some erroring code ...
} catch (err) {
    try {
        log.error({ error: err });
    } catch (err2) {
        console.error('oops', err2); // oops TypeError: Message must be a string.
    }
}
```

it would be nice if the docs mentioned that the message is required.
