### ISSUE TITLE
printf message formatting broken

### ISSUE THREAD

**Issue by andrew-property-xyz** [gajus/roarr#36]
I have just upgraded the version of roarr logger from 2.15.4 to 3.2.0 within a Node 12.19.0 application.

I make use of printf message formatting extensively throughout the application. With v2.15.4, I had not encountered any issues with this. For example:

```log.debug('Processing feed [%s] for %d agents', feedId, agentCount)```

would work perfectly and output something like this:

```Processing feed [abc123] for 25 agents```

With roarr v3.2.0, however, the output is this:

```Processing feed [abc123] for %d agents```

In fact, the behaviour I am observing is that all substitution variables apart from the first one seem to be completely ignored.

To resolve the issue, I reverted to roarr v2.15.4.

**Comment by gajus** [comment]
Yikes. Looks like http://npmjs.com/sprintfit only supports `%s` interpolation.

**Comment by gajus** [comment]
Fixed in https://github.com/gajus/roarr/commit/5e264c947c712223c5aeeceb0b95edb04bd0acef
