### ISSUE TITLE
Error when using Roarr version > 4 with Node 16

### ISSUE THREAD

**Issue by ayltai** [gajus/roarr#45]
I just started a new project with create-react-app, added Roarr, and configured it according to the readme (https://github.com/gajus/roarr#roarr-usage). When I ran `npm start`, I got a "Failed to compile" error.

The error was: "Can't resolve 'async_hooks'" in:
https://github.com/gajus/roarr/blob/master/src/factories/createRoarrInitialGlobalState.ts#L34

This error happens if I use Roarr versions 5.0.0, 6.0.0, and 7.0.0. Version 4.2.5 works fine.

**Environment:**
node: 16.4.2
npm: 7.19.1
macOS: 11.4

**Comment by gajus** [comment]
Node.js v16 has [`async_hooks`](https://nodejs.org/api/async_hooks.html).

Is this a node.js project or are you using webpack or anything similar?

**Comment by ayltai** [comment]
I'm using create-react-app so it's webpack. Thanks for applying the workaround so quickly. I just tried version 7.0.1 and it works. The APIs works though it still complains it couldn't resolve 'async_hooks' in the console.

**Comment by gajus** [comment]
If you are getting this error when bundling using CRA, then this is likely an issue with `detect-node` falsely detecting webpack as node.js (CC @iliakan)
