### ISSUE TITLE
Logs written with AsyncLocalStorage are not written to stdout when running on k8s pods

### ISSUE THREAD

**Issue by deankevorkian** [gajus/roarr#46]
Hey! Glad I found this library. I enjoy it and have been using it for a while for some pet projects.

Lately, I've been trying to use roarr to write logs to the stdout stream, which are later collected by fluentd and written to our Elastic.

When locally running a Nodejs express api that uses roarr (we create a log child for each log level and add some different context properties depending on the log level) the logs get printed to the console. However, when deploying that api to a k8s cluster, the logs do not appear on the pod logs, and as a result are not collected by fluentd.

I took some time to try and investigate whether or not any of this has to do with AsyncLocalStorage. I thought it might run in a slightly different context and might point to a different stdout, and so forgive my ignorance as this is only an assumption and I haven't used this Node API before.

When downgrading to the last stable version before AsyncLocalStorage, the issue is not reproduced and logs are successfully written (that is, version 4.2.5).

Could you please help shed some light on where you thing this issue resides? I'd be happy to jump in and open a PR to fix this but I do not know for sure that it in fact happens due to the use of this Node API.

Thanks! (feel free to change the issue title as this is an assumption)

**Comment by gajus** [comment]
> When locally running a Nodejs express api that uses roarr (we create a log child for each log level and add some different context properties depending on the log level) the logs get printed to the console. However, when deploying that api to a k8s cluster, the logs do not appear on the pod logs, and as a result are not collected by fluentd.

Are you using the same version of Node.js locally and in k8s?

**Comment by gajus** [comment]
Closing as this is most likely simply an issue of unsupported Node.js version.

**Comment by deankevorkian** [comment]
Hey!
Apparently the issues we had were just related to the fact that the ROARR_LOG environment variable was missing. So, the stdout, AsyncLocalStorage and other conspiracy theories we brought up were false alarmed. Sorry for that.

However, after fixing that, we found another issue, unrelated to the library - when collecting logs with fluentd, from the log streams of our pods on our k8s cluster, the messages would not be transferred to Elastic. Seems like this happens due to fluentd having issues collecting the json parsed log messages, when the json contains a property by name of "time". I am still unsure if this is default fluentd behavior, or something faulty in our own configuration.

However, I'd like to know if it's possible to provide another API in the library where one could manipulate the structure of the json (for that matter, choosing different property names for the object written by Roarr).

For now, we will simply patch the write method to parse the stringified json back to an object, rename the property and strigify it again.

**Comment by deankevorkian** [comment]
Keep this issue close, I'll open a seperate one for the last part I wrote.
