### ISSUE TITLE
Logging message together with error object

### ISSUE THREAD

**Issue by gaastonsr** [gajus/roarr#5]
Hi! I'm using roarr in a project and I think it's great.

I have a question, if I want to log an error message together with a message, how would you do it?

Example: I'm trying to send an email and it returns an error.

```js
mailer.send(email, error => {
  if (error) {
    logger.error('Error sending email'); // here I want log the serialized error too
  }
});
```

**Comment by gajus** [comment]
https://github.com/gajus/roarr#logging-errors

**Comment by gaastonsr** [comment]
Awesome example! thank you.
