### ISSUE TITLE
Why "Roarr"?

### ISSUE THREAD

**Issue by DiamondeX2** [gajus/roarr#51]
Maybe this is a stupid question, but I think that somewhere at the start of Readme it should be explained

**Comment by gajus** [comment]
It is actually covered in one of the introductory articles.

https://medium.com/free-code-camp/roarr-the-perfect-json-logger-node-js-and-browser-935180bda529#e6fc

> What about the name?
> I got some initial critique about the use of a generic, “cutesy” name such as “roarr”. The primary reason for choosing the name is to identify the package as loud. Roarr logs cannot be suppressed, just like the roar of a tiger.
> _You’re gonna hear me roar!_
> From the practical perspective, “ROARR” is a safe term to grep and reserve in the global environment.

**Comment by DiamondeX2** [comment]
Thanks for an answer
