### ISSUE TITLE
Add warnOnce and other methods

### ISSUE THREAD

**Issue by gajus** [gajus/roarr#62]

**Comment by gajus** [comment]
Just saw @sebinsua implement similar pattern.

https://github.com/sebinsua/modern-node-app/blob/main/src/core/roarrLogger/roarrLogger.ts

**Comment by gajus** [comment]
@sebinusa Can you please take a look at https://github.com/gajus/roarr/pull/65 before it is merged?

**Comment by sebinsua** [comment]
Yeah, I will!
