### ISSUE TITLE
Need to upgrade the major version number?

### ISSUE THREAD

**Issue by dbit-xia** [gajus/roarr#72]
Hello, I see that the fast-json-stringify that the new version roarr@7.14.1 depends on has been upgraded to 5.5.0, but the @fastify/deepmerge it depends on requires node14 to run, which makes the version <node14 unable to run. Does roarr Should a major version be upgraded?

deepmerge/index.js uses the syntax "?."

**Comment by indeyets** [comment]
@gajus please. can you fix BC break here?

**Comment by gajus** [comment]
I am not clear what is the issue here. Are you saying that one of the dependencies broke compatibility with Node v14?

**Comment by dbit-xia** [comment]
Yes,roarr package.json 
```
"engines": {
    "node": ">=12.0"
  },
```

but, node v12 doesn't work!

**Comment by gajus** [comment]
That is an oversight. However, these node versions are no longer under active support.

https://endoflife.date/nodejs

**Comment by indeyets** [comment]
@gajus 

- 7.14.0 was compatible with Node-12
- 7.14.1 is not compatible with Node-12

would be nice to release 7.14.2 which is compatible with Node-12 again (for legacy systems) and release 8.0.0 which breaks this compatibility

**Comment by gajus** [comment]
Can you confirm that the latest version works in node v12?

**Comment by indeyets** [comment]
@gajus yes, thank you! seems to work fine now
