### ISSUE TITLE
Printing maps to logger output

### ISSUE THREAD

**Issue by hertg** [gajus/roarr#8]
I am currently using Node 9.5.0.
Unfortunately it seems that i can't print Maps with this logger.

```typescript
let map: Map<string, number[]> = new Map();
map.set("some key", [1,2,3]);
map.set("another key", [1]);
map.set("the third key", [3]);
log.debug({map: map, keys: map.keys(), values: map.values()}, " theres no output here");
```

however, with `console.log(map);` i can print all of its content.

**Comment by gajus** [comment]
You can define a custom middleware for printing maps.

See:

* https://github.com/gajus/roarr#middlewares
*https://github.com/gajus/roarr-middleware-serialize-error (Example of a middleware.)
