### ISSUE TITLE
No logging inside Docker containers

### ISSUE THREAD

**Issue by PlkMarudny** [gajus/roarr#80]
I just noticed that there is no logging in the containerized SvelteKit application. console.log(...) produces log, while roarr does not. I am trying to log from the server part of an app with a Node backend. ROARR_LOG seems to be set inside the container (it is done via docker-compose.yaml file (and from the container shell I can see it being set properly).

**Comment by gajus** [comment]
Add `console.log(process.env.ROARR_LOG)` to debug further.

That's the only setting that controls if output should be produced.
