### ISSUE TITLE
Newest version does not log anything

### ISSUE THREAD

**Issue by pkoniu** [gajus/roarr#9]
So I have two projects. I introduced `roarr` to the first one some time ago when the newest version available was `2.0.2` and everything works smoothly there. Today I wanted to introduce it to the other application and currently the newest release is `2.2.0`. There's no difference in logger-related code in both applications and `roarr` in version `2.2.0` does not log anything. Here's the snipper from entrypoint to the app:
``` javascript
process.env.ROARR_LOG = true;
const roarr = require('roarr');
const logger = roarr.default;
logger('test-one');
logger.child({test:true}).info('test-two');
```
WIth `2.0.2` no problems, I get the following output:
```
{"context":{},"message":"test-one","sequence":0,"time":1526456311629,"version":"1.0.0"}
{"context":{"test":true,"logLevel":30},"message":"test-two","sequence":1,"time":1526456311631,"version":"1.0.0"}
```

With `2.2.0` I get nothing.

**Comment by gajus** [comment]
It is probably in the buffer.

See https://github.com/gajus/roarr#environment-variables.

Configuring `ROARR_BUFFER_SIZE=0` would restore the original behaviour.

I think though that I made mistake by making buffering the new default. It can result in unexpected behaviour if user is unaware of the buffereing.

Let me change the defaults.

Enabling buffering is a good idea, though.

**Comment by gajus** [comment]
Fixed.

Sorry about the confusion.
